In [1]:
# Welcome to your new notebook
# Type here in the cell editor to add code!
print ("Hello SQL Bits!")

StatementMeta(, 07f2272f-00ce-4322-b808-3374734cff68, 3, Finished, Available)

Hello SQL Bits!

In [1]:
import pandas as pd

# Series == Array of elements/items
series = pd.Series([1001, 1002, 1003, 1004, 1005])

print(series)

StatementMeta(, e18bf709-ae8a-434c-8388-036d557d126a, 3, Finished, Available)

0    1001
1    1002
2    1003
3    1004
4    1005
dtype: int64

In [2]:
from datetime import date, datetime, timedelta

# Dataframe == Dictionary + Series
dataframe = pd.DataFrame(
  {
    'OrderID':      [1001, 1002, 1003, 1004, 1005],
    'CustomerID':   [5, 3, 2, 4, 6],
    'OrderDate':    [date(2023,3,2), date(2023,3,15),date(2023,3,30), date(2023,4,2), date(2023,4,11)],
    'ShipDate':     [date(2023,3,6), date(2023,3,16),date(2023,4,1), date(2023,4,6), date(2023,4,15)],
    'CustomerName': ['John', 'Mike','Jane', 'Tom', 'Angela'],
    'ProductID':    [101, 202, 203, 404, 606],
    'Qty':          [1, 2, 1, 4, 10],
    'Price':        [2.15, 2.59, 4.08, 1.55, 3.54]
  }
)
dataframe.info()

StatementMeta(, e18bf709-ae8a-434c-8388-036d557d126a, 4, Finished, Available)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       5 non-null      int64
 1   CustomerID    5 non-null      int64
 2   OrderDate     5 non-null      object
 3   ShipDate      5 non-null      object
 4   CustomerName  5 non-null      object
 5   ProductID     5 non-null      int64
 6   Qty           5 non-null      int64
 7   Price         5 non-null      float64
dtypes: float64(1), int64(4), object(3)
memory usage: 448.0+ bytes

In [4]:
# Cast the Date columns to datetime data type
dataframe['OrderDate'] = dataframe['OrderDate'].astype('datetime64[ns]')
dataframe['ShipDate']  = dataframe['ShipDate'].astype('datetime64[ns]')
dataframe.info()

StatementMeta(, e18bf709-ae8a-434c-8388-036d557d126a, 6, Finished, Available)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       5 non-null      int64
 1   CustomerID    5 non-null      int64
 2   OrderDate     5 non-null      datetime64[ns]
 3   ShipDate      5 non-null      datetime64[ns]
 4   CustomerName  5 non-null      object
 5   ProductID     5 non-null      int64
 6   Qty           5 non-null      int64
 7   Price         5 non-null      float64
dtypes: datetime64[ns](2), float64(1), int64(4), object(1)
memory usage: 448.0+ bytes

In [5]:
import math
import numpy as np


# Column == Series
seriesQty = dataframe['Qty'] 
seriesPrice = dataframe['Price'] 

# Use Vectorized Operations to create Calculated Columns
seriesLineTotal        = dataframe['Qty'] * dataframe['Price']
dataframe['LineTotal'] = dataframe['Qty'] * dataframe['Price'] 

# Error:math.ceil() only works for scalar values
dataframe['LineTotal'] = math.ceil(dataframe['Qty'] * dataframe['Price']) 
# Correct: np.ceil() support Vectorized Operations
dataframe['LineTotal'] = np.ceil(dataframe['Qty'] * dataframe['Price'])

#dataframe['Year'] = dataframe['OrderDate'].year # Wrong series doesn't have a year property!
dataframe['Year'] = dataframe['OrderDate'].dt.year
dataframe['LeadTime'] = (dataframe['ShipDate'] - dataframe['OrderDate']).dt.days

dataframe['Lower'] = dataframe['CustomerName'].str.lower()
dataframe['FirstUpper'] = dataframe['CustomerName'].str[0].str.upper() 

display(dataframe)

StatementMeta(, e18bf709-ae8a-434c-8388-036d557d126a, 7, Finished, Available)

TypeError: cannot convert the series to <class 'float'>

In [6]:
# Get DataFrame Schema
dataframe.info()

# Get # of rows and columns
print( dataframe.shape )                   # (5,6)   

# Get Columns
print(dataframe.columns)

StatementMeta(, e18bf709-ae8a-434c-8388-036d557d126a, 8, Finished, Available)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       5 non-null      int64
 1   CustomerID    5 non-null      int64
 2   OrderDate     5 non-null      datetime64[ns]
 3   ShipDate      5 non-null      datetime64[ns]
 4   CustomerName  5 non-null      object
 5   ProductID     5 non-null      int64
 6   Qty           5 non-null      int64
 7   Price         5 non-null      float64
 8   LineTotal     5 non-null      float64
dtypes: datetime64[ns](2), float64(2), int64(4), object(1)
memory usage: 488.0+ bytes
(5, 9)
Index(['OrderID', 'CustomerID', 'OrderDate', 'ShipDate', 'CustomerName',
       'ProductID', 'Qty', 'Price', 'LineTotal'],
      dtype='object')

In [7]:
# Iterate throug all the rows
for ind, item in dataframe.iterrows():
  print(f'Index: {ind} Brand: {item["brand"]}')

StatementMeta(, e18bf709-ae8a-434c-8388-036d557d126a, 9, Finished, Available)

KeyError: 'brand'

In [ ]:
#print( dataframe[0] )                    # wrong 
print( dataframe.brand )                  # All data in brand column
print( dataframe['brand'] )               # All data in brand column
print( dataframe['brand'][0:3] )          # First 3 items in brand column
print( dataframe[['passings','brand'  ]]) # All rows with passing and brand column